apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hyland-employees
  description: All Hyland employees
  annotations:
    github.com/project-slug: HylandExperience/hyland-developers-portal
    backstage.io/techdocs-ref : dir:.
    # Use the plugin’s fully‑qualified annotation keys:
    jira.atlassian.net/project-key: FCCSEU
    jira.hyland.atlassian.net/dashboard-url: https://hyland.atlassian.net/jira/software/c/projects/FCCSEU/summary

spec:
  type: service
  profile:
    displayName: Hyland Employees
    email: hyland-employees@hyland.com
    picture: https://example.com/groups/hyland-employees.png
  parent: hyland
  children: []
  members:
    - user:default/indranjana
