apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: new_groups
  description: |
    New groupss
  annotations:
    github.com/project-slug: HylandExperience/fcc-seu-orchestrator
    backstage.io/techdocs-ref: dir:.
    jira.com/project-key: FCCSEU
    jira.com/board-name: FCC-SEU Content Repo Module Package Squad
    confluence.com/space-key: HFCH
    confluence.com/page-id: '2664696869'
spec:
  type: team
  profile:
    displayName: New group
    email: new@hyland.com
    picture: https://www.adobe.com/content/dam/cc/us/en/creativecloud/illustration-adobe-illustration/how-to-draw-trees/draw-trees_fb-img_1200x800.jpg
  owner: hyland
  parent: CRMP_SQUAD
  children: []
  members: [harry]
