apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: indranjana
  annotations:
    github.com/user-id: "214480286"
spec:
  profile:
    displayName: Indranjana
    email: ""
    picture: https://avatars.githubusercontent.com/u/214480286?v=4
  memberOf:
    - hyland-employees
    - Admin
    - CRMP_SQUAD

