
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dfgh
  annotations:
    github.com/user-id: "1258"
spec:
  profile:
    displayName: Dfgh
    email: Indranjana.Chatterjee@hyland.com
    picture: 
  memberOf: [abcd]
